# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    upload_folder: '%kernel.project_dir%/public/medias' # Info de réf dans l'app pour le dossier uploads
    GEMINI_KEY: '%env(GEMINI_KEY)%' # Info de réf dans l'app pour la clé openai depuis le .env

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\EventListener\ArticleListener:
        tags:
            - { name: 'doctrine.event_listener', event: 'postPersist', entity: 'App\Entity\Article', method: 'onArticleCreated' }
            - { name: 'doctrine.event_listener', event: 'postUpdate', entity: 'App\Entity\Article', method: 'onArticleUpdated' }
            - { name: 'doctrine.event_listener', event: 'postRemove', entity: 'App\Entity\Article', method: 'onArticleDeleted' }

    # Déclaration de UserListener écoutant l'événement de connexion Symfony
    App\EventListener\UserListener:
        tags:
            - { name: 'kernel.event_listener', event: 'security.interactive_login', method: 'onUserLogin' }
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones